apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: another-one-gitops
  description: This is GitOps manifest for another-one   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: another-one
    janus-idp.io/tekton: another-one 
    backstage.io/kubernetes-id: another-one 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:another-one
