apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: another-one
  janus-idp.io/tekton: another-one
  backstage.io/kubernetes-id: another-one
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: another-one
resources:
- deployment.yaml
- route.yaml
- service.yaml
