apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: another-one
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: another-one 
  name: another-one
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: another-one 
